
language: python

python:
  - { PATH: "{{replace(Python35, '\\', '\\\\')}}", VERSION: 3.5, DIST: std }
  - { PATH: "{{replace(Python36, '\\', '\\\\')}}", VERSION: 3.6, DIST: std }
  - { PATH: "{{replace(Python27, '\\', '\\\\')}}", VERSION: 2.7, DIST: std }
  - { PATH: "{{replace(Anaconda3, '\\', '\\\\')}}", VERSION: 3.6, DIST: conda }
  - { PATH: "{{replace(Anaconda2, '\\', '\\\\')}}", VERSION: 2.7, DIST: conda }
  - { PATH: "{{replace(WinPython36, '\\', '\\\\')}}", VERSION: 3.6, DIST: winpython }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
  
install:
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ jyquickhelper pyquickhelper --extra-index-url=https://pypi.python.org/simple/
  - pip install -r requirements.txt
  - python --version
  - pip freeze
  - pip freeze > pip_freeze.txt

before_script:
  - if [ ${VERSION} == "2.7" ] then pip uninstall jyquickhelper fi
  - if [ ${VERSION} == "2.7" ] then pip install bin\jyquickhelper-0.2-py2-none-any.whl fi
  - if [ ${VERSION} == "2.7" ] then {{Python35}}\python -u setup.py copy27 fi
  - if [ ${VERSION} == "2.7" ] then cd dist_module27 fi
  
script:
  - { CMD: "python -u setup.py unittests", NAME: "UT", TIMEOUT: 900 }
  - { CMD: "python -u setup.py unittests_SKIP", NAME: "UT_SKIP", TIMEOUT: 900 }
  - if [ ${VERSION} == "3.5" and ${DIST} == "std" ]
      then 
        --CMD=python -u setup.py build_sphinx;
        --NAME=DOC;
      fi

after_script:
  - python -u setup.py bdist_wheel
  - if [ ${VERSION} == "2.7" and ${DIST} != "conda" ] then copy dist\*.whl {{root_path}}\..\..\local_pypi\local_pypi_server fi
  - if [ ${VERSION} == "2.7" ] then cd .. fi
  - if [ ${VERSION} != "2.7" and ${DIST} != "conda" and ${VERSION} == "3.5" and ${NAME} == "UT" ] then copy dist\*.whl {{root_path}}\..\..\local_pypi\local_pypi_server fi

# Same as after script.
documentation:
  - if [ ${NAME} == "UT" and ${VERSION} != "2.7" ] then python -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" and ${VERSION} != "2.7" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\html dist\html fi
